import { test, expect } from '@playwright/test';
import LoginPage from '../pages/login_page';
import inventoryPage from '../pages/inventory_page';
import pages from '../utils/pages';

test('test', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="username"]').press('Tab');
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.locator('[data-test="password"]').press('Enter');
  await page.locator('[data-test="login-button"]').click();
  await page.locator('[data-test="title"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="continue-shopping"]').click();
  await page.locator('[data-test="footer-copy"]').click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('[data-test="social-linkedin"]').click();
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  await page.locator('[data-test="social-facebook"]').click();
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  await page.locator('[data-test="social-twitter"]').click();
  const page3 = await page3Promise;
  await expect(page.locator('[data-test="inventory-item-description"]').first()).toBeVisible();
  await expect(page.locator('[data-test="item-4-img-link"]')).toBeVisible();
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await expect(page.locator('[data-test="about-sidebar-link"]')).toBeVisible();
  await expect(page.locator('[data-test="inventory-sidebar-link"]')).toBeVisible();
  await expect(page.locator('[data-test="logout-sidebar-link"]')).toBeVisible();
  await expect(page.locator('[data-test="reset-sidebar-link"]')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Close Menu' })).toBeVisible();
  await expect(page.locator('[data-test="product-sort-container"]')).toBeVisible();
  await expect(page.locator('[data-test="shopping-cart-link"]')).toBeVisible();
  await expect(page.locator('[data-test="inventory-container"]')).toBeVisible();
});